mv 'v_ 2.jpg' 'V_ 2.jpg' 
mv 'v_ 3.jpg' 'V_ 3.jpg'
mv 'v_ 4.jpg' 'V_ 4.jpg'
mv 'v_ 5.jpg' 'V_ 5.jpg'
mv 'v_ 6.jpg' 'V_ 6.jpg'
mv 'v_ 7.jpg' 'V_ 7.jpg'
mv 'v_ 8.jpg' 'V_ 8.jpg'
mv 'v_ 9.jpg' 'V_ 9.jpg'
mv 'v_ 10.jpg''V_ 10.jpg'
